### ISSUE TITLE
Error adding Roomba if bravva's are detected

### ISSUE THREAD

**Issue by MartinJRS** [bloomkd46/homebridge-iRobot#34]
### Roomba Model:

981

### Did It Work

No

**Comment by MartinJRS** [comment]
It tells me to have received my Braava's IP ... but doesn't mention the Roomba 981. In the plugin settings, under "devices" there are no devices shown to select.

Thanks

**Comment by bloomkd46** [comment]
Yes, this is a problem that I have been trying to fix. It will only add devices until it hits a incompatible/undefined device

**Comment by bloomkd46** [comment]
This problem should be fixed, please open a bug report if it isn't

**Comment by MartinJRS** [comment]
Thanks ... have tested it, but unfortunately it still doesn't work for me.

[iRobot] Logging into iRobot...
[iRobot] Configuring roomba: Braava Jet M6
[iRobot] Configuring roomba: Roomba 981
[iRobot] Ignoring Unconfigured Roomba: Braava Jet M6

Still, in the plugin settings, under "devices" there are no devices shown to select.

**Comment by bloomkd46** [comment]
Does the device ever show up in HomeKit?

**Comment by MartinJRS** [comment]
No, it doesn't ... likely I am doing something wrong here?

**Comment by bloomkd46** [comment]
No, it looks like it is discovering the Roomba but failing to return it, I will look into it later today

**Comment by MartinJRS** [comment]
Oh wow, that's very kind ... thanks many times. Good luck ;)

**Comment by MartinJRS** [comment]
Guessing it to be a bit complicated. Any news yet?

**Comment by bloomkd46** [comment]
I have read that bravva jets supposedly work. So I whitelisted them in beta version `2.1.17-beta.1`. Could you please try it out and let me know if it works?

**Comment by MartinJRS** [comment]
Hey, sorry for my late response. Yeah, I can confirm this. In beta both, Roomba as well as Braava is working fine 😉 Nicely done. Thank you
