### ISSUE TITLE
Bug Report: TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by shivanathd** [bloomkd46/homebridge-iRobot#99]
### Describe The Bug:

When starting the bridge, I get the error listed : TypeError: Cannot read properties of undefined (reading 'name')

### To Reproduce:

I configured the plugin using auto config

### Expected behavior:

for the plugin to start 

### Logs:

```shell
[2/21/2022, 3:26:30 AM] [iRobot] Configuring roomba: Braava jet FF
[2/21/2022, 3:26:30 AM] [iRobot] Configuring roomba: Roomba GF
[2/21/2022, 3:26:30 AM] [iRobot] Configuring roomba: Braava jet GF
[2/21/2022, 3:26:30 AM] [iRobot] Disabling Unconfigured Roomba: Braava jet FF
[2/21/2022, 3:26:30 AM] Homebridge v1.4.0 (HAP v0.10.0) (iRobot) is running on port 55100.
TypeError: Cannot read properties of undefined (reading 'name')
    at getRoombas (/usr/local/lib/node_modules/homebridge-irobot/src/getRoombas.ts:50:63)
    at iRobotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-irobot/src/platform.ts:65:36)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-irobot/src/platform.ts:34:12)
    at HomebridgeAPI.emit (node:events:520:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:173:14)
```

### Config:

```shell
{
    "name": "iRobot",
    "email": "***email",
    "password": "***password",
    "roombas": [
        {
            "autoConfig": true,
            "info": {
                "ver": 2
            }
        }
    ],
    "manualDiscovery": false,
    "lowBattery": 10,
    "offAction": "pause:dock",
    "status": "phase:run",
    "eveStatus": "inverted:cycle:clean",
    "bin": "filter:contact",
    "ignoreMultiRoomBin": true,
    "hideStuckSensor": false,
    "disableMultiRoom": true,
    "platform": "iRobotPlatform"
}
```

### Node Version:

v16.14.0

### NPM Version:

8.3.1

### Homebridge Version:

1.4.0

### Plugin Version:

 v2.1.16

### Operating System:

MacOS

**Comment by shivanathd** [comment]
<img width="332" alt="Screenshot 2022-02-21 at 3 36 55 AM" src="https://user-images.githubusercontent.com/1937549/154866380-7653ad05-56f4-4a61-b631-4329038f5293.png">

here's the directory its talking about, I don't see an src folder

**Comment by shivanathd** [comment]
Updated to the latest Beta and that error goes away.. but I get this error on home bridge logs

[homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

**Comment by shivanathd** [comment]
This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: undefined. See https://git.io/JtMGR for more info.

**Comment by bloomkd46** [comment]
I will be releasing a new beta either tonight or tomorrow that works very well

**Comment by bloomkd46** [comment]
I just published a new beta that should be stable

**Comment by MaleNurse** [comment]
Updated to beta 11 but this error is still showing up in my log.

**Comment by bloomkd46** [comment]
Try clearing any homebridge-iRobot devices from your cache

**Comment by MaleNurse** [comment]
Unfortunately, the error is still there after removing them from the cache.

**Comment by bloomkd46** [comment]
Please try the latest beta: [![npm](https://img.shields.io/npm/v/homebridge-irobot/beta?label=beta)](https://github.com/bloomkd46/homebridge-iRobot/wiki/Beta-Version)
